language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install -U pipenv
  - pip install -U codecov

install:
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install -d

script:
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv --ignore-run python -m pytest

after_success:
  - codecov
