language: python
python:
  - "3.7"

install:
  - pip install --user pipenv
  - pipenv install -d

script:
  - pipenv run python -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .coverage
